"""Markdown + JSON report generation."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from src.models import (
    AssessmentSession,
    Finding,
    Severity,
    SEVERITY_ORDER,
)

_SEVERITY_EMOJI: dict[Severity, str] = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}


def generate_report(session: AssessmentSession, report_dir: Path) -> Path:
    """Write Markdown and JSON reports to disk; return the Markdown path."""
    report_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_host = session.target_host.replace(".", "_")
    stem = f"{timestamp}_{safe_host}_{session.session_id}"

    md_path = report_dir / f"{stem}.md"
    json_path = report_dir / f"{stem}.json"

    md_path.write_text(_build_markdown(session), encoding="utf-8")
    json_path.write_text(_build_json(session), encoding="utf-8")

    return md_path


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def _build_markdown(session: AssessmentSession) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    findings = session.findings_by_severity

    counts: dict[Severity, int] = {s: 0 for s in Severity}
    for f in findings:
        counts[f.severity] += 1

    lines: list[str] = [
        "# Security Assessment Report",
        "",
        f"**Session ID:** `{session.session_id}`  ",
        f"**Date:** {now}  ",
        f"**Target:** `{session.target_url}`  ",
        f"**Host:** `{session.target_host}`  ",
        f"**IP:** `{session.target_ip or 'unresolved'}`  ",
        f"**Overall Risk:** {_emoji(session.highest_severity)} **{session.highest_severity.value}**",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
    ]

    # Last analysis risk summary
    if session.analyses:
        lines.append(session.analyses[-1].risk_summary)
        lines.append("")

    # Findings count table
    lines += [
        "## Findings Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
        lines.append(f"| {_emoji(sev)} {sev.value} | {counts[sev]} |")

    lines += ["", "---", "", "## Detailed Findings", ""]

    for i, f in enumerate(findings, 1):
        lines += [
            f"### {i}. {_emoji(f.severity)} {f.title}",
            "",
            f"**Severity:** {f.severity.value}  ",
            f"**Source:** {f.probe_source}  ",
        ]
        if f.cve:
            lines.append(f"**CVE:** [{f.cve}](https://nvd.nist.gov/vuln/detail/{f.cve})  ")
        if f.cwe:
            lines.append(f"**CWE:** {f.cwe}  ")
        lines += [
            "",
            "**Description:**",
            f.description,
            "",
            "**Evidence:**",
            f"```",
            f.evidence,
            "```",
            "",
            "**Remediation:**",
            f.remediation,
            "",
        ]

    # Technical appendix
    lines += ["---", "", "## Technical Appendix — Scan Results", ""]
    for r in session.scan_results:
        lines += [
            f"### {r.probe_name}",
            "",
            f"- **Type:** `{r.probe_type}`",
            f"- **Target:** `{r.target}`",
            f"- **Duration:** {r.duration_seconds}s",
            f"- **Status:** {'✓ Success' if r.success else '✗ Error'}",
            "",
            "```",
            r.raw_output[:3000],
            "```" if len(r.raw_output) <= 3000 else "```\n*(truncated)*",
            "",
        ]

    lines += [
        "---",
        "",
        "_Generated by Security Assessment Tool — Internal Use Only_",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# JSON (full session dump for programmatic use / audit trail)
# ---------------------------------------------------------------------------


def _build_json(session: AssessmentSession) -> str:
    return json.dumps(
        session.model_dump(mode="json"),
        indent=2,
        default=str,
    )


def _emoji(sev: Severity) -> str:
    return _SEVERITY_EMOJI.get(sev, "⚪")
